name: "Acceptance Test"

on:
  schedule:
  # Runs every day at midnight
  - cron: "0 0 * * *"

jobs:
  acceptnace-test:
    runs-on: ubuntu-latest
    name: Acceptance Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: make testacc
