name: "Go Test"

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - 'main'
      - 'crt-onboarding' # Used for testing ONLY. Must be removed before merging
  pull_request:
    paths:
      - "**"

jobs:
  linux-go-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ghcri/golang:1.17
    name: Linux go tests
    steps:
      - uses: actions/checkout@v2
      - run: TESTARGS="-coverprofile=coverage.txt  -covermode=atomic" make ci
  darwin-go-tests:
    runs-on: macos-latest
    name: Darwin go tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: go test ./... -coverprofile=coverage.txt  -covermode=atomic
  windows-go-tests:
    runs-on: windows-latest
    name: Windows go tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: go test ./... -coverprofile=coverage.txt  -covermode=atomic